---
- hosts: nginx
  become: yes
  become_method: sudo
  vars:
    remote_tmpfile: /var/lib/jenkins/workspace/Jenkins/index.html
    remote_tmpapps: /var/www/html/
  tasks:
  - name: stop service httpd 
    service:
     name: httpd
     state: stopped
  - name: copy the file 
    synchronize: src={{remote_tmpfile}}  dest={{remote_tmpapps}}
  - name: Start service httpd, if not started
    service:
     name: httpd
     state: started
